### PR TITLE
Add support for OCaml 5.0

### PR DESCRIPTION
**Pull request by kit-ty-kate**
I'm not sure if the tests are complete but at least calling `dune runtest` does not fail (exit 0)

### CODE REVIEW

**Comment by rdicosmo** [comment]
Thanks @kit-ty-kate !

**Comment by kit-ty-kate** [comment]
Would it be possible to make a release soon by any chance? The final release of OCaml 5.0 is planned for the first week of december and having it released beforehand would help a lot.

I can do the release on opam-repository if you need, i just need a tag to hold on to.

**Comment by rdicosmo** [comment]
Thanks Kate, that would be great, I'll create a tag over the weekend

**Comment by rdicosmo** [comment]
@kit-ty-kate : just pushed the tag https://github.com/rdicosmo/parmap/releases/tag/1.2.5
if you are so kind as to create the opam package, I would be grateful!

**Comment by kit-ty-kate** [comment]
This is now published in opam-repository (https://github.com/ocaml/opam-repository/pull/22576)

**Comment by rdicosmo** [comment]
Thanks @kit-ty-kate !

**Pull request merged**
