### PR TITLE
Dune support

### PR DESCRIPTION
**Pull request by olafhering**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
I think the clean way to move to dune is to rely on those two packages:
- https://github.com/UnixJunkie/setcore
- https://github.com/UnixJunkie/bytearray
and get rid of the uggly discover.ml file that you are introcuding (too reminiscent of the uggly myocamlbuild.ml files that people were forced to live with).

- setcore is useful to other libraries (parany, for example)
- bytearray might be useful to other people who need high performance serialization of arrays

**Comment by olafhering** [comment]
`setcore` will receive the very same changes: every autoconf will be removed in the future.

**Comment by olafhering** [comment]
@rdicosmo any opinion on this set of changes?

**Comment by rdicosmo** [comment]
Thanks for taking the time to contribute, and sorry for the long silence, I'm in the middle of practically uninterrupted travel until mid-november. 
To help me assess the proposal, would you mind summing up the overall approach with its pros and cons? I promise I'll take the time to look into all this.

**Comment by XVilka** [comment]
Since @UnixJunkie deprecated setcore, should it be updated to use https://github.com/UnixJunkie/cpu ?

**Comment by olafhering** [comment]
I think you have to discuss this depreciation in a separae issue.

This one is for dune. And as I learned the `*.opam` file has to stay, to assist `opam`. So I will one more refresh.

About the reasoning: `oasis` is not maintained anymore. `dune` is maintained. When there is an `ocaml.exe` there is also a `dune.exe`. In case pre-ocaml 4.02 has to be supported, the switch to dune can not be done.

**Comment by UnixJunkie** [comment]
@XVilka note that the setcore opam package was never used by a released version of parmap.
I created the package to make the functionality available to other packages and to simplify parmap's code base.
Recently, I renamed the setcore opam package to cpu, so that I can coinstall parmap with other packages that use the same module but under a different name (cpu now).
Otherwise, the compiler was generating some errors and it was not possible to install parmap with the latest version of parany, for example.

**Comment by Drup** [comment]
Sometimes, trying too hard to be modular is counterproductive. Both the `setcore` and the `bytearray` modules were intended for internal use, and not to be split into small packages for public consumption. They are not polished and, in the case of `bytearray`, there are (several!) far more polished packages for this already existing.

@olafhering 's version is self-contained, only use dunes, get rids of autoconf, m4 and whatnot, is compatible from ocaml 4.02 to 4.09, and the code is clean. Let's merge it and stop worrying. :)

**Comment by UnixJunkie** [comment]
@olafhering you should contact @rdicosmo if you want to take over the maintenance of parmap

**Comment by rdicosmo** [comment]
Thanks @olafhering for the great cleanup/update, now merged into mainline.

**Comment by olafhering** [comment]
> @olafhering you should contact @rdicosmo if you want to take over the maintenance of parmap

I think I touched just the buildsystem. I'm not in the position to maintain this pkg.

**Pull request merged**
