### PR TITLE
4.08.0 fixes because of Bigarray.map_file moved to the Unix module

### PR DESCRIPTION
**Pull request by UnixJunkie**
Do not merge.

### CODE REVIEW

**Comment by glondu** [comment]
> Do not merge.

Why?

**Comment by UnixJunkie** [comment]
Because this will not compile anymore on old ocaml versions.

**Comment by glondu** [comment]
Ah, right. I guess the mmap opam package was made for this kind of situation...

**Comment by UnixJunkie** [comment]
Nice idea, but then why this mmap package has an ocaml version constraint: "ocaml" {>= "4.02.3"}.

@rdicosmo up to how old an ocaml version do you want to support?

**Comment by aantron** [comment]
I don't know why the 4.02.3 constraint is in `mmap.opam` at this point. It probably shouldn't be there. But 4.02 is a constraint of Dune anyway: https://github.com/ocaml/dune/blob/master/dune.opam#L30

**Comment by rdicosmo** [comment]
Thanks everybody for looking into all this.

Since the feature set is now fairly stable I am fine with having a newer
version of Parmap that requires OCaml >= 4.0: do not hesitate in moving
forward and drop pre 4.0 compatibility from now on

Roberto

**Comment by diml** [comment]
@glondu because I only tested the build with OCaml >= 4.02.3

**Comment by UnixJunkie** [comment]
superseded by https://github.com/rdicosmo/parmap/pull/88

**Pull request closed without merging**
