### PR TITLE
Fixes for compilation w 4.03.0

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
I could not run the tests. I don't even remember how to launch them.

**Comment by UnixJunkie** [comment]
@shindere

**Comment by rdicosmo** [comment]
Thanks Francois!
    that's just make; make install; make tests :-)

2016-04-27 10:19 GMT+02:00 Francois Berenger <notifications@github.com>:

> I could not run the tests. I don't even remember how to launch them.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rdicosmo/parmap/pull/38#issuecomment-215008101>
>



-- 
Roberto Di Cosmo

------------------------------------------------------------------
Professeur (on leave at/detache a INRIA Roquencourt)
IRIF                           email : roberto@dicosmo.org
Universite Paris Diderot         web : http://www.dicosmo.org
Case 7014                    Twitter : http://twitter.com/rdicosmo
5, Rue Thomas Mann
F-75205 Paris Cedex 13 FRANCE
------------------------------------------------------------------
Office location:

Paris Diderot                       INRIA

Bureau 3020 (3rd floor)             Bureau C123
Batiment Sophie Germain             Batiment C
8 place Aurélie Nemours             2, Rue Simone Iff
Tel: +33 1 57 27 92 20              Tel: +33 1 80 49 44 42

Metro
 Bibliotheque F. Mitterrand        Ligne 6: Dugommier
 ligne 14/RER C                    Ligne 14/RER A: Gare de Lyon
------------------------------------------------------------------
GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3

**Comment by UnixJunkie** [comment]
Apparently they run then. I don't see any ERROR message.

**Comment by rdicosmo** [comment]
Great! Now, we cannot ship this version right away, as it will break in all
previous versions of the compiler that do not support annotations etc.

I'm committing right away the fix for the blocking issue, that is moving
setcore.mli to setcore.ml, and the type annotations, that are not compiler
version dependent.

We probably need to create then a  parmap.ml.in and a bytearray.ml.in as
template to instantiate into "noalloc" or [@@noalloc] and into Byte. or String.
the relevant parts that are compiler dependent.

Francois, would you give it a try?

--
Roberto

**Comment by UnixJunkie** [comment]
For the "Great" part: in opam, we can constrain the compiler version.

I don't like boilerplate things.
If you only take the file move, then all the rest are just warnings.

**Comment by rdicosmo** [comment]
May you split your pull request in two parts:
  - one with the file move and the msg_to_master type constraint (this can be merged immediately)
  - one with the other part of the fixes

**Comment by UnixJunkie** [comment]
Right away. Just give me 10mn.

**Comment by rdicosmo** [comment]
Ok, thanks Francois.... closing this, which is superceded by your two new pull requests.

**Pull request closed without merging**
