### PR TITLE
added test for ocamlbuild

### PR DESCRIPTION
**Pull request by UnixJunkie**
Maybe the configure file needs to be regenerated, if my proposed change is correct

### CODE REVIEW

**Comment by UnixJunkie** [comment]
related to https://github.com/rdicosmo/parmap/issues/78

**Comment by w-simon** [comment]
Hi @UnixJunkie , 
It might be simpler to modify the code here.
Thanks.

diff --git a/configure.ac b/configure.ac
index d0ee512..970ad3e 100644
--- a/configure.ac
+++ b/configure.ac
@@ -4,6 +4,9 @@ AC_PROG_OCAML
 if test "$OCAMLC" = "no"; then
  AC_MSG_ERROR([You must install the OCaml compiler])
 fi
+if test "$OCAMLBUILD" = "no"; then
+ AC_MSG_ERROR([You must install OCamlbuild (the ocamlbuild command)])
+fi

 AC_PROG_FINDLIB
 AC_SUBST(OCAMLFIND)

**Comment by UnixJunkie** [comment]
If you know better, please send a proper PR.
@rdicosmo can merge the best one.
I am not an autoconf expert.

**Comment by w-simon** [comment]
Hi @UnixJunkie ,Thank you.
I send a another PR #80 .
Code modification under your inspiration, since the AC_DEFUN ([AC_PROG_OCAML] code fragment in the m4/ocaml.m4 file has detected the existence of OCAMLBUILD, it is not necessary to define AC_PROG_OCAMLBUILD again.
Thanks.

**Pull request closed without merging**
